language : java
install :
script :
    - cd core
    - mvn install
    - cd ../example
    - ant
    - java -cp bin:../core/target/config-1.4.jar:$HOME/.m2/repository/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar Example
    - cd ../core
cache :
    directories : "$HOME/.m2"
deploy:
  provider: script
  script: "cp ../.travis.settings.xml $HOME/.m2/settings.xml && mvn jar:jar deploy:deploy || :"
  skip_cleanup: true
jdk : oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
    email : false
